services:
  dev:
    networks:
      - shared_network
    container_name: ambassador-dev
    build: .
    command: [ "bash", "/app/start_dev.sh" ]
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - DEBUG=True
    depends_on:
      redis:
        condition: service_started

  prod:
    networks:
      - shared_network
    container_name:
      ambassador-prod
    build: .
    command: ["bash", "/app/start_prod.sh"]
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
    restart: always
    volumes:
      - .:/app

  redis:
    image: redis:7
    container_name: ambassador-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - shared_network

volumes:
  postgres_data:

networks:
  shared_network:
    external: true
