# Generated by Django 5.2.6 on 2025-10-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=16)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('comments', models.TextField(blank=True)),
                ('contact_name', models.CharField(max_length=64)),
                ('restaurant_organisation_name', models.CharField(max_length=64)),
                ('ghl_contact_id', models.CharField(blank=True, max_length=32, null=True)),
                ('ghl_opportunity_id', models.CharField(blank=True, max_length=32, null=True)),
                ('deal_completed', models.BooleanField(default=False)),
                ('claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
