# Generated by Django 5.2.6 on 2025-09-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='invited_by_prospect',
        ),
    ]
