# Generated by Django 5.2.6 on 2025-10-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='ghl_location_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
