# Generated by Django 5.2.6 on 2025-09-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0002_remove_prospect_invited_by_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='contact_name',
            field=models.CharField(default=str, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospect',
            name='deal_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prospect',
            name='first_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospect',
            name='ghl_contact_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='ghl_opportunity_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='last_name',
            field=models.CharField(default='1', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospect',
            name='restaurant_organisation_name',
            field=models.CharField(default='1', max_length=64),
            preserve_default=False,
        ),
    ]
