# Generated by Django 5.2.6 on 2025-10-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0003_prospect_comments_prospect_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
