# Generated by Django 5.2.6 on 2025-10-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0004_prospect_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='phone',
            field=models.CharField(max_length=16),
        ),
    ]
