# Generated by Django 5.2.6 on 2026-05-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0004_alter_prospect_invited_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='ghl_opportunity_id',
        ),
    ]
