# Generated by Django 5.2.6 on 2025-10-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0005_alter_prospect_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
