# Generated by Django 5.2.6 on 2025-10-21 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prospect', '0006_prospect_claimed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_of_frylows', models.IntegerField(default=0)),
                ('prospect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prospect.prospect')),
            ],
        ),
    ]
