# Generated by Django 5.2.6 on 2025-10-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_tree_level', models.PositiveSmallIntegerField()),
                ('number_of_frylows', models.IntegerField(default=0)),
            ],
        ),
    ]
