# Generated by Django 5.2.6 on 2025-10-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commission', '0001_initial'),
        ('prospect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='prospect.prospect'),
        ),
    ]
