# Generated by Django 5.2.6 on 2025-10-22 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0002_remove_commission_claimed_and_more'),
        ('prospect', '0006_prospect_claimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='prospect.prospect'),
        ),
    ]
