# Generated by Django 5.2.6 on 2025-11-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='money_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='commission',
            name='number_of_frylows',
            field=models.PositiveIntegerField(),
        ),
    ]
