# Generated by Django 5.2.6 on 2025-11-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0004_commission_currency_commission_money_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commission',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
