# Generated by Django 5.2.6 on 2025-10-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_code_bundles',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
