# Generated by Django 5.2.6 on 2025-09-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_code_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
