# Generated by Django 5.2.6 on 2025-10-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_qr_code_bundles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qr_code_bundles',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
