# Generated by Django 5.2.6 on 2025-09-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_qr_code_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='qr_code_id',
            new_name='referral_qr_code_id',
        ),
    ]
