# Generated by Django 5.2.6 on 2025-09-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_qr_code_id_user_referral_qr_code_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.TextField(blank=True, verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='contact name'),
        ),
        migrations.AddField(
            model_name='user',
            name='restaurant_organisation_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='restaurant organisation name'),
        ),
    ]
