# Generated by Django 5.2.6 on 2025-10-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_qr_code_bundles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='organization name'),
        ),
    ]
