# Generated by Django 5.2.6 on 2025-09-29 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_is_verified_user_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent_path',
        ),
        migrations.RemoveField(
            model_name='user',
            name='restaurant_organisation_name',
        ),
        migrations.AddField(
            model_name='user',
            name='invited_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_prospect',
            field=models.BooleanField(default=False),
        ),
    ]
