# Generated by Django 5.2.6 on 2025-12-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_stripe_account_id_user_stripe_onboard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_user_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
