# Generated by Django 5.2.6 on 2026-01-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_apple_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skip_invitation_code_input',
            field=models.BooleanField(default=False),
        ),
    ]
