# Generated by Django 5.2.6 on 2026-03-24 11:21

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_skip_invitation_code_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_mail_chimp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, validators=[utils.validators.validate_human_name], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, validators=[utils.validators.validate_human_name], verbose_name='last name'),
        ),
    ]
