# Generated by Django 5.2.6 on 2026-07-05 08:14

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_in_mail_chimp_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[utils.validators.validate_human_name], verbose_name='last name'),
        ),
    ]
